# Generated by Django 6.0.4 on 2026-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('base_salary', models.IntegerField()),
                ('marital_status', models.CharField(max_length=50)),
                ('children', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('risk_type', models.CharField(max_length=100)),
                ('bonuses', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('total', models.IntegerField()),
                ('retirement', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('deductions', models.IntegerField()),
                ('social_security', models.IntegerField()),
                ('net_salary', models.IntegerField()),
            ],
        ),
    ]
