# Generated by Django 6.0.4 on 2026-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='engineering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='final_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='professional',
            field=models.IntegerField(default=0),
        ),
    ]
