# Generated by Django 6.0.5 on 2026-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_allowances_employee_engineering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('employment_type', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=50)),
                ('appointment_order', models.CharField(max_length=100)),
                ('appointment_order_date', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('basic_salary', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('last_bonus', models.CharField(max_length=50)),
                ('last_promotion', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('graduation_year', models.CharField(max_length=20)),
                ('service_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
